# Generated by Django 5.1.2 on 2024-10-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('encryption_method', models.CharField(max_length=50)),
                ('encrypted_content', models.TextField()),
                ('hashed_content_sha256', models.CharField(max_length=64)),
                ('hashed_content_bcrypt', models.TextField()),
            ],
        ),
    ]
